import type { Plugin } from 'vite';
import { loadEnv } from 'vite';
import fs from 'node:fs';
import path from 'node:path';

function buildMessagingSwSource(env: Record<string, string>): string {
  const apiKey = env.VITE_FIREBASE_API_KEY || env.VITE_CUSTOM_FIREBASE_API_KEY || '';
  const projectId = env.VITE_FIREBASE_PROJECT_ID || '';
  const messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID || '';
  const appId = env.VITE_FIREBASE_APP_ID || '';

  return `/* Generated by viteFirebaseMessagingSw — do not edit manually. */
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: ${JSON.stringify(apiKey)},
  projectId: ${JSON.stringify(projectId)},
  messagingSenderId: ${JSON.stringify(messagingSenderId)},
  appId: ${JSON.stringify(appId)},
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || 'Travel Muse';
  const options = {
    body: payload.notification?.body || '',
    icon: '/favicon.ico',
    data: payload.data,
  };
  self.registration.showNotification(title, options);
});
`;
}

/** Embeds VITE_FIREBASE_* into firebase-messaging-sw.js for FCM background handling. */
export function viteFirebaseMessagingSw(): Plugin {
  let env: Record<string, string> = {};

  return {
    name: 'vite-firebase-messaging-sw',
    config(_config, { mode }) {
      env = loadEnv(mode, process.cwd(), '');
    },
    configureServer(server) {
      server.middlewares.use('/firebase-messaging-sw.js', (_req, res) => {
        res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
        res.setHeader('Service-Worker-Allowed', '/');
        res.end(buildMessagingSwSource(env));
      });
    },
    writeBundle() {
      const outDir = path.resolve(process.cwd(), 'dist');
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(
        path.join(outDir, 'firebase-messaging-sw.js'),
        buildMessagingSwSource(env),
        'utf8',
      );
    },
  };
}
